name: Docker Image Build

on:
  push:
    branches:
      - 'master'

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    #strategy:
      #matrix: ${{ steps.diff_files.outputs.files }}
        #dockerfile: [terraform/0.11/Dockerfile, terraform/0.11/Dockerfile]
        #dockerfile: ${{ fromJSON(env.DIFF_FILES) }}
    outputs:
      matrix_json: ${{ steps.output_data.outputs.matrix_json }}
    steps:

      - name: Check out
        uses: actions/checkout@v2
        
      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: |
            ./terraform/*
          FILES: |
            Dockerfile
          
      - name: set output
        id: output_data
        shell: bash
        run: |
             matrixJsonObject=$(echo $MATCHED_FILES | jq --raw-input --raw-output 'gsub("'"'"'"; "") | split(" ") | map( { Dockerfile:.} ) | { include:. } | tostring') 
             echo $matrixJson 
             echo "::set-output name=matrix_json::$matrixJsonObject"
     
     
      - name: check output
        run: echo ${{ steps.output_data.outputs.matrix_json }}

      # - name: diff files
      #   id: diff_files   
      #   if: env.GIT_DIFF
      #   shell: bash     
      #   run:  | 
      #     . script.sh
             

  docker:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix_json) }}
    steps:
      # - run: echo Run ${{ matrix.Dockerfile }}
      # - run: echo ${{ fromJson(needs.build_matrix.outputs.matrix_json) }}
      # - run: echo ${{ needs.build_matrix.outputs.matrix_json }}
      # - name: check
      #   run:
      #     echo   $matrix_json
      #     echo ${{ needs.build_matrix.outputs.matrix_json }}
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.3.0
        with:
          images: ghcr.io/SadriG91/concourse-terraform
          tags: |
            type=sha
            type=edge
            type=semver,pattern={{version}}, value=v0.14.5    
                    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: file=$(echo "./${{ matrix.Dockerfile }}")
      - run: echo "./"${{ matrix.Dockerfile }}     
      - name: Build and push Docker images
        #if: env.GIT_DIFF
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }} 
          file: ./${{ matrix.Dockerfile }} 
          
          